name: servant-docs-blaze
version: 0.0.0.0
synopsis: Generate HTML documentation for Servant APIs
description: Please check out the README for more information.
homepage: https://github.com/Airsequel/servant-docs-blaze#readme
license: AGPL-3.0-or-later
author: Adrian Sieber
maintainer: adrian@feram.io
copyright: Adrian Sieber
category: Web

extra-source-files:
  - readme.md

dependencies:
  - base
  - protolude

default-extensions:
  - NoImplicitPrelude
  - OverloadedRecordDot
  - OverloadedStrings

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans

library:
  language: GHC2021
  source-dirs: source
  dependencies:
    - aeson
    - aeson-pretty
    - blaze-html
    - blaze-markup
    - bytestring
    - http-media
    - raw-strings-qq
    - servant-docs
    - text
    - unordered-containers

tests:
  servant-docs-blaze-test:
    language: GHC2021
    source-dirs: tests
    main: Spec.hs
    dependencies:
      - aeson
      - aeson-pretty
      - blaze-html
      - blaze-markup
      - bytestring
      - hspec
      - http-media
      - raw-strings-qq
      - servant
      - servant-docs
      - servant-docs-blaze
      - servant-server
      - text
